name: First action

on:
    workflow_dispatch:
    push:
      paths:
        - docs/*
    pull_request:
      branches:
        - docs/*
  
jobs:
    first:
      runs-on: ubuntu-latest
      permissions:
        contents: write
        id-token: write
        pages: write
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Install Python and Dependencies
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'
            cache: 'pip'
        - run: python3 -m pip install jupyter
        - run: pip install json-schema-for-humans
        - run: generate-schema-doc --config template_name=md docs/*.json README.md
        - run: generate-schema-doc  docs/*.json index.html 
        - name: Update files
          run: |
            git config --global user.email yan.ping.chen.lin@iqb.hu-berlin.com
            git config --global user.name nanoyan
            git add --all -- :!docs/*
            git commit -m 'Update the static page html'
            git push origin master --force
          
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}